# -*- coding: utf-8 -*-
"""stream_csv_genrator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hhGCqszXgJn7K39oRlkm24bz_mA_wc70
"""

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/synthetic_aqi.csv'

import csv
import random
from datetime import datetime, timedelta

# Settings
num_days = 10000
start_date = datetime(2024, 1, 1)

# Helper to generate fluctuating AQI
def generate_aqi_trend(i):
    base = 100 + 30 * (i % 10 >= 5) - 15 * (i % 20 == 0)  # periodic up/down
    noise = random.randint(-10, 10)
    return max(0, base + noise)

# Generate increasing PM2.5 max values
def generate_pm25(i):
    return min(500, int(50 + (i * 2) + random.randint(-10, 10)))  # increasing trend

# Other components fluctuate randomly
def random_component(avg, variance=20):
    return max(0, int(avg + random.gauss(0, variance)))

# Write to the CSV in Google Drive
with open(file_path, mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["date", "aqi", "pm2_5", "pm10", "no2", "so2", "co", "o3"])

    for i in range(num_days):
        date = start_date + timedelta(days=i)
        pm25 = generate_pm25(i)
        aqi = generate_aqi_trend(i)
        row = [
            date.strftime("%Y-%m-%d"),
            aqi,
            pm25,
            random_component(80),
            random_component(40),
            random_component(30),
            round(random.uniform(0.5, 2.0), 2),
            random_component(60)
        ]
        writer.writerow(row)

print(f"synthetic_aqi.csv file has been created in your Google Drive at {file_path}.")

from google.colab import drive
import csv
import math
import random
from datetime import datetime, timedelta

# Step 1: Mount Google Drive
drive.mount('/content/drive')

# Step 2: Set the file path to your Drive
file_path = "/content/drive/My Drive/water_quality_stream.csv"

# Step 3: Dataset settings
num_days = 10000
start_date = datetime(2024, 1, 1)

# Step 4: Generators
def generate_ph(i):
    drift = 0.5 * math.sin(2 * math.pi * i / 3650)
    noise = random.uniform(-0.1, 0.1)
    return round(7 + drift + noise, 2)

def generate_turbidity(i):
    base = 5 + 2 * math.sin(2 * math.pi * i / 365)
    spike = random.uniform(0, 5) if random.random() < 0.02 else 0
    return round(base + spike, 2)

def generate_dissolved_oxygen(i):
    seasonal = 9 + 1.5 * math.cos(2 * math.pi * i / 365)
    noise = random.uniform(-0.2, 0.2)
    return round(seasonal + noise, 2)

# Step 5: Write CSV to Drive
with open(file_path, mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["date", "ph", "turbidity", "dissolved_oxygen"])

    for i in range(num_days):
        date = start_date + timedelta(days=i)
        writer.writerow([
            date.strftime("%Y-%m-%d"),
            generate_ph(i),
            generate_turbidity(i),
            generate_dissolved_oxygen(i)
        ])

print(f"✅ File saved to: {file_path}")

